version: '3'

services:

  web:
    container_name: pedidocs
    restart: always
    build: .
    ports:
      - "8080:5000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
